### PR TITLE
First pass at API documentation

### LINKED ISSUE #530: API documentation
I am having a very difficult time using vexflow due to either me not finding the proper location for the API documentation or maybe these docs are missing.

Just having an API wiki specifying function arguments would be a huge help...

For example, I cannot find documentation on

1. note durations (from a number representing a fraction of a whole note)
2. creating rests

### PR DESCRIPTION
**Pull request by tmcw**
Fixes #530 

This implements API documentation for VexFlow. It's not adding any new
prose - only converting existing comments to JSDoc-style comments,
moving certain comments to position them correctly.

Adds one new dependency:

- documentation

Adds two new npm run scripts:

- dev-docs: build & serve HTML docs
- docs: build Markdown docs into API.md

Adds documentation output: API.md

---

Note that my time commitment here needs to stay pretty low: I have a
full-time job, significant side projects, and ongoing open source
commitments, so I don't have the bandwidth to get to 100% documentation
coverage or anything like that.

But I think this PR as it stands is enough for new contributors to jump in,
add more documentation, and find more old-fashioned comments that can just be
converted to JSDoc and start showing up in the docs.

### CODE REVIEW

**Comment by gristow** [comment]
On a quick glance this looks great -- I'll pull and check it out locally in the next day or two, but I agree this is an excellent start towards jsdoc style API documentation. Thanks!

**Comment by mix3d** [comment]
No Updates, eh?

**Comment by rvilarl** [comment]
@0xfe what is your oppinion on /** */ style comments? They do integrate great with VSCode to get the funtion details just by hover

**Comment by 0xfe** [comment]
I'm good with that.

**Comment by rvilarl** [comment]
> I'm good with that.

@0xfe should I include the change in #861 already?

**Comment by rvilarl** [comment]
@tmcw would you still like to collaborate on this one? We could re use a lot of your work

**Comment by rvilarl** [comment]
@0xfe now that we use typedoc, I think you can close this PR

**Pull request closed without merging**
