### PR TITLE
issue 1469 - get top Y for top annotation

### PR DESCRIPTION
**Pull request by AaronDavidNewman**
Small change, when annotation placement is 'top', get the final entry in the `note.Ys()`, since that will have the (numerically lowest, screen highest) Y value.  Previously, it was always getting entry [0] which is the numerically highest, staff-lowest pitch.

old:
image

new test case:
image

I am upgrading my Ubuntu VM right now so I can't do visual diff.  But this will only affect cases with multiple pitch keys and stem up, and we didn't have any test cases for that.

### CODE REVIEW

**Comment by rvilarl** [comment]
LGTM

**Comment by rvilarl** [comment]
@AaronDavidNewman I checked the output after merging and this has a bug. Two examples:

Annotation Harmonics Bravura
Annotation Harmonics Bravura_current
Annotation Harmonics Bravura_reference
Annotation Simple_Annotation Bravura
Annotation Simple_Annotation Bravura_current
Annotation Simple_Annotation Bravura_reference

**Comment by AaronDavidNewman** [comment]
Huh...maybe Ys for tab clef are not sorted?  If so, @StevenSchuerstedt had it correct that we should just reduce to the smallest value.

**Comment by rvilarl** [comment]
Should I revert the changes in annotation.ts & chordsymbol.ts?

**Comment by AaronDavidNewman** [comment]
No, I will push another PR shortly.  I am running the visual regression tests now.

**Pull request merged**
