### PR TITLE
More formatter improvements: better general purpose behavior.

### PR DESCRIPTION
**Pull request by 0xfe**
- Add support for accumulation of deviations for single-pass tuning.
- Add deviations for beam groups. (Not used yet.)
- Add additional tests for tuning.
- Some refactoring.
### Example 1 (before/after)

See better evenness in bottom stave.

### Example 2 (before/after)

See better evenness in bottom stave.

### CODE REVIEW

**Comment by Silverwolf90** [comment]
Other than the minor conflict, is this ready to go in?

**Comment by 0xfe** [comment]
I've paged a bunch of this state out of my brain, so lets hold off on this. I'll dig in more soon.

**Comment by gristow** [comment]
So, I'm getting ready to do some revisions on beaming to make automatic beaming really work with time signatures in a more natural way. Given the extensive work you did on `beam.js` in this PR, @0xfe, I wonder if we wanted to revisit merging this before I dive into beams?

**Comment by 0xfe** [comment]
Thanks Gregory. The changes to `beam.js` here are not very invasive, so I'd say go ahead with your beaming work. (Thanks for checking.)

**Comment by 0xfe** [comment]
Formatting completely overhauled, and we now have awesome formatting without using the tuner.

Screen Shot 2020-04-17 at 7 13 12 PM
Screen Shot 2020-04-17 at 7 12 49 PM
Screen Shot 2020-04-17 at 7 12 18 PM

### New voice parameter 'softmaxFactor` controls the proportion suppresion

Here's 50, 150, 250, 350, and 450, side-by-side. (Default is 100.)

Screen Shot 2020-04-17 at 7 12 29 PM

**Pull request closed without merging**
