### PR TITLE
reduce jsdom_jobs on platform with many cpus.

### PR DESCRIPTION
**Pull request by h-sug1no**
@0xfe san

thank you for merge #1268 and sorry to bother you.

this PR reduce the jsdom_jobs on platform with many cpus.
for example my MBP has 12 logical cpus. 

It seems that 12 is a bit much for jodom_jobs, so limiting it to pptr_jobs will speed up the process by a few seconds.

### CODE REVIEW

**Comment by h-sug1no** [comment]
I don't know why check failed: https://github.com/0xfe/vexflow/runs/4636217023?check_suite_focus=true#step:5:42

qunit:files task runs with no error on my local environment as follows... :
```
Running "qunit:files" (qunit) task
Testing tests/flow-headless-browser.html ...
.........................................................................................................................................................................................................OK
>> 1615 tests completed with 0 failed, 0 skipped, and 0 todo. 
>> 7194 assertions (in 15849ms), passed: 7194, failed: 0

Done.
```

**Comment by 0xfe** [comment]
Looks like:

```
Running "qunit:files" (qunit) task
Testing tests/flow-headless-browser.html FF
>> global failure
>> Message: Script error.
>> Actual: null
>> Expected: undefined
>> :0

>> global failure
>> Message: Uncaught ReferenceError: Vex is not defined
>> Actual: null
>> Expected: undefined
>> file:///home/runner/work/vexflow/vexflow/tests/flow-headless-browser.html:12

Warning: 2 tests completed with 2 failed, 0 skipped, and 0 todo. 
2 assertions (in 10ms), passed: 0, failed: 2 Use --force to continue.

Aborted due to warnings.
Error: Process completed with exit code 6.
```

**Comment by 0xfe** [comment]
Not sure which PR broke the build -- not related to this PR.

**Comment by h-sug1no** [comment]
filed #1274

**Comment by h-sug1no** [comment]
All checks have passed. ready for review.

**Comment by 0xfe** [comment]
Looks good, thanks!

**Pull request merged**
