### PR TITLE
scale stem length like flag to fix too short stem: [644 gracenote stem flag]

### PR DESCRIPTION
**Pull request by sug1no**
* #644
* scale stem length like flag to fix too short stem
* add grace_notes arg to GraceNoteGroup.beamNotes() to render multiple beams.

```
% npm test
...

You have 2 warning(s):
  Warning: Grace_Notes.Grace_Note_Stem.svg missing in ./build/images/blessed.
  Warning: Grace_Notes.Grace_Note_Stem_with_Beams.svg missing in ./build/images/blessed.
You have 10 fail(s):
Grace_Notes.Grace_Note_Basic_with_Slurs 26.4707
Grace_Notes.Grace_Note_Basic 5.43178
Percussion.Percussion_Basic1 2.72808
Percussion.Percussion_Snare1 2.70336
Percussion.Percussion_Notes 1.53046
Percussion.Percussion_Basic2 1.41165
Accidental.Automatic_Accidentals 0.780145
Percussion.Percussion_Basic0 0.287374
Grace_Notes.Grace_Notes_Multiple_Voices_Multiple_Draws 0.145915
Grace_Notes.Grace_Notes_Multiple_Voices 0.145915
```

* I think GraceNote* and Accidental* are effected by this PR. diff images and new test images:

image

* I think stem length is better now.

* but the beam of the normal note collides with the beam of the grace note (also with finale...). Is this problem serious? :

### CODE REVIEW

**Comment by 0xfe** [comment]
Thanks @sug1no -- there were a few WIP commits after the PR. Is this ready for review?

**Comment by sug1no** [comment]
>  there were a few WIP commits after the PR. Is this ready for review?

Sorry for the confusing comments. this is ready for review.

**Comment by 0xfe** [comment]
Looks great. Merging.

**Comment by mscuthbert** [comment]
" the beam of the normal note collides with the beam of the grace note (also with finale...). Is this problem serious?" -- yes, it's a serious problem for performers, but as we weren't detecting it automatically before, the fact that it comes up a little more often now doesn't make it a problem that this PR needs to solve.  In these cases, manual stem-length tweaks are necessary and acceptable.

**Comment by sug1no** [comment]
@mscuthbert san: 

> but as we weren't detecting it automatically before, the fact that it comes up a little more often now doesn't make it a problem that this PR needs to solve. In these cases, manual stem-length tweaks are necessary and acceptable.

I understand. Thanks for your detailed answer.

**Pull request merged**
