### PR TITLE
 stroke outline of NoteHeads

### PR DESCRIPTION
**Pull request by shimondoodkin**
just implemented stroke outline of NoteHeads

not sure how to check if it goes well with other things

not sure how to add it to documentation

I had a need to for bi-colored notes to color colored notes of sharp notes

colorednotes

### CODE REVIEW

**Comment by shimondoodkin** [comment]
I believe it is safe to merge, and will not be interfering with other things.

usage:
staveNote.setKeyStyle(noteIndex, {fillStyle: color, headStrokeStyle:color2, headStrokeWidth:3 });

**Comment by SalahAdDin** [comment]
@shimondoodkin Awesome!

**Comment by impactcolor** [comment]
@shimondoodkin is there an update to the new notehead.js?
I tried to integrate your update but the notehead.js file has changed

**Comment by ronyeh** [comment]
Just looking through old PRs. I agree there should be more flexible ways to style individual glyphs.

However, I would suggest that we "archive" (i.e., close) this since the last activity is over four years ago. If there is new momentum to make this happen, we can open a new PR and reference this one.

**Comment by 0xfe** [comment]
Agreed.

**Pull request closed without merging**
