### PR TITLE
Test notehead displacements after changing stem direction

### PR DESCRIPTION
**Pull request by Silverwolf90**

### CODE REVIEW

**Comment by 0xfe** [comment]
Thanks... where's `deepEqual` coming from? It breaks the visual regression tests.

**Comment by Silverwolf90** [comment]
https://api.qunitjs.com/deepEqual/

Oddly thought it's not breaking on my machine, both in the browser and in the command line.

**Comment by Silverwolf90** [comment]
Ah! Does my latest commit fix it?

**Comment by 0xfe** [comment]
Yes, fixed, thanks. Merging.

**Pull request merged**
