### PR TITLE
#551 add slash bases

### PR DESCRIPTION
**Pull request by Bigsby**
#551 
Adding ability to add bass notes to harmonic text.

### CODE REVIEW

**Comment by mscuthbert** [comment]
changes look good to me.

**Comment by 0xfe** [comment]
Thanks. Can you add a test please? (and paste in some sample output images)

**Comment by Bigsby** [comment]
> Thanks. Can you add a test please? (and paste in some sample output images)

Sure. That should be fun.

**Comment by 0xfe** [comment]
Closing stale request. Please reopen when you're ready.

**Pull request closed without merging**
