### PR TITLE
Migrate EasyScoreTests

### PR DESCRIPTION
**Pull request by ronyeh**
No test differences from master.

Two open questions:

1) Some of the test cases directly accessed instance variables that are now marked as `protected`. Does that mean we should unprotect those variables (i.e., was public access to those variables part of the official API)? I ended up using the available getters, and defined a new getter where needed (e.g., `getFretHandFinger()`).

2) I am having trouble directly referencing the `EasyScore` or `Articulation` classes. It results in runtime error. For example, I can do `console.log(FretHandFinger)` but I **CANNOT** do `console.log(Articulation)` or `console.log(Articulation.CATEGORY)` or `console.log(EasyScore)`. I get the following error (some searching suggests maybe circular imports??):

```
vexflow-tests.js:13379 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at ./src/gracenote.ts.__extends (vexflow-tests.js:13379)
    at vexflow-tests.js:13403
    at Object../src/gracenote.ts (vexflow-tests.js:13557)
    at __webpack_require__ (vexflow-tests.js:30)
    at Object../src/dot.ts (vexflow-tests.js:2842)
    at __webpack_require__ (vexflow-tests.js:30)
    at Object../src/stavenote.ts (vexflow-tests.js:15554)
    at __webpack_require__ (vexflow-tests.js:30)
    at Object../src/easyscore.ts (vexflow-tests.js:3013)
    at __webpack_require__ (vexflow-tests.js:30)

vexflow-tests.js:12920 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at ./src/gracenote.ts.__extends (vexflow-tests.js:12920)
    at vexflow-tests.js:12944
    at Object../src/gracenote.ts (vexflow-tests.js:13098)
    at __webpack_require__ (vexflow-tests.js:30)
    at Object../src/dot.ts (vexflow-tests.js:2842)
    at __webpack_require__ (vexflow-tests.js:30)
    at Object../src/stavenote.ts (vexflow-tests.js:14852)
    at __webpack_require__ (vexflow-tests.js:30)
    at Object../src/articulation.ts (vexflow-tests.js:2247)
    at __webpack_require__ (vexflow-tests.js:30)
```

### CODE REVIEW

**Comment by rvilarl** [comment]
Hi I also had this problem on another project and it was indeed a circular dependencies problem. I had to end up including all the files on single file common.ts as:
export * from './A'; 
export * from './B';
export * from './C'; ....

The all the different files would import the required function/classes from this common.ts.

However I suggest that I finish the elimination of the vex dependecies and we see if we still have the problem.

@ronyeh is the failure output above from the terminal or from the developers' console in Chrome?

**Comment by ronyeh** [comment]
Chrome dev console. It compiled fine.

Anyways, I didn't reference those two problematic classes directly in this
PR, so it can be merged. After you're done migrating Vex, I can go back and
clean up this test file to use Articulations.CATEGORY directly, etc.

Let me know if you need any help with the vex.js.

**Comment by rvilarl** [comment]
> Let me know if you need any help with the vex.js.

I believe that vex.js will be easy to finish once Mohit merges the next migration/utils, we will see. I will not forget the offer. :)

**Comment by 0xfe** [comment]
Looks good.

@rvilarl I think that migration/utils has conflicts?

**Comment by 0xfe** [comment]
This one has conflicts too :-)

**Comment by ronyeh** [comment]
OK, conflict resolved!

**Comment by 0xfe** [comment]
Great!

**Pull request merged**
