### PR TITLE
ES6 class syntax and babel integration

### PR DESCRIPTION
**Pull request by aaronmars**
Refactor to use ES6 class (and related) syntax.
Shuffled the structure of the sources to all follow the structure as discussed in issue https://github.com/0xfe/vexflow/issues/359

### CODE REVIEW

**Comment by Silverwolf90** [comment]
`accidental`, `stavenote`, `formatter`, `modifiercontext` all good to me

**Comment by 0xfe** [comment]
Thanks aaron, can we limit the PR to just the four files, so it's easier to review and merge?

**Comment by Silverwolf90** [comment]
@0xfe for the sake of reviewing, [I copied over those 4 files to this branch for an isolated comparison](https://github.com/0xfe/vexflow/compare/master...Silverwolf90:four-files). But github really doesn't do large diffs well, you're better off pulling the branch locally and diffing the files individually imo.

If you're content with these files as a representative sample, unit tests and visual regression tests pass, I would suggest merging this PR

**Comment by aaronmars** [comment]
Oh man, thanks.  I am in the middle of doing exactly the same thing.  I appreciate the help, and can still prepare any configuration you need.

Sorry again for mis-reading the initial request.

**Comment by 0xfe** [comment]
Okay, so I went through everything -- it didn't end up taking to long. Everything looks great, I love the new syntax. Merging.

Thanks a lot for the great work, Aaron!

(Also thanks for helping with the review, Cyril.)

**Pull request merged**
