### PR TITLE
Migration/4.0

### PR DESCRIPTION
**Pull request by rvilarl**
Issues 1 & 2 described in #1200 resolved:
1) imports without path -> Solution: Path added
2) legacy fonts in src directory -> Solution: Legacy moved to tools/fonts/
3) @Bravura, @gonville, @petaluma ... -> Workaround: change to './fonts/loadStatic'

3 needs still to be resolved

eslint warnings resolved

### CODE REVIEW

**Comment by ronyeh** [comment]
Sorry, maybe it's late and I don't understand. :-) 

Are any of these fixes duplicated in my other PR about build process, and also my Font PR? I don't want to have us overwriting each others changes when a merge happens.

**Comment by ronyeh** [comment]
For example, I also moved the legacy font tools out, and I also updated them to work again with the new Font PR branch. I anticipate some bad rebase / merges coming soon :-}.

**Comment by rvilarl** [comment]
No this independent. You asked me to give it a go with `npm link`. This the changes I had to make it work see #1200. Of course I placed out the fonts where you did.

Changes apart from including the path in the imports are minor in this PR.

**Comment by ronyeh** [comment]
Hey if you have time can you try **npm link**ing to my setFont branch? I just tested today's rebase over master, and it is showing no visual diffs.

I'd like to see what public API things I may have broken, and which things my branch does better than the current master.

Unfortunately I don't have a fancy app like yours to integrate with my branch. Your app is very nice! I'll try to some musicxml with it next week.

Here's my branch:
https://github.com/ronyeh/vexflow/tree/setFont

I'm currently reviewing your setFontMinor PR, and then I'll head to bed.

**Comment by rvilarl** [comment]
I did it already, results are in #1200 have a look there :)

**Comment by rvilarl** [comment]
legacy changes merged from #1163 to avoid files being overwritten

**Comment by rvilarl** [comment]
ready to review

**Comment by ronyeh** [comment]
We should try to solve the `@xxxxx` paths issue before proceeding I think. Here is a related discussion. https://github.com/microsoft/TypeScript/issues/25677

I need to do more research as I'm sure someone has developed a solution via a webpack plugin or something. 

In my font PR, I've consolidated your 
```
@bravura
@gonville
@petaluma
@custom
```
into a single

```
@loadFonts
```

Since your @ paths before were all pointed to the same module anyways.

**Comment by rvilarl** [comment]
> We should try to solve the `@xxxxx` paths issue before proceeding I think. Here is a related discussion. [microsoft/TypeScript#25677](https://github.com/microsoft/TypeScript/issues/25677)
> 
> I need to do more research as I'm sure someone has developed a solution via a webpack plugin or something.
> 
> In my font PR, I've consolidated your
> 
> ```
> @bravura
> @gonville
> @petaluma
> @custom
> ```
> 
> into a single
> 
> ```
> @loadFonts
> ```
> 
> Since your @ paths before were all pointed to the same module anyways.

I left them separted to allow possible combinations (ie.: Brabura static and others dynamic) In any case this is not related to this PR. :)

**Comment by rvilarl** [comment]
@0xfe Ready to review

**Comment by ronyeh** [comment]
I'd recommend that this is the next PR to be reviewed and merged. I'm happy to be the last blocker for shipping a 4.0 beta. 🥇 hahah. But I think we are close. Rodrigo has been testing some of my recent builds with his PianoPlay project.

**Comment by 0xfe** [comment]
Thanks for this. Looks good. Merging. (Is there a tslint plugin that will auto-order the imports?)

**Comment by rvilarl** [comment]
@0xfe yes! it is already merged! All was sorted automatically!

**Comment by ronyeh** [comment]
> Thanks for this. Looks good. Merging. (Is there a tslint plugin that will auto-order the imports?)

Yes, we discussed last week and Rodrigo and I chose the "eslint-plugin-simple-import-sort": "^7.0.0".

It has just a few options that you can set in .eslintrc. In my Fonts branch, I'm now using the config below. It will autofix imports, combine duplicates if possible, add newlines, and sort them based on your provided array of regex. I just used the default sort order, but moved the two imports that start with "vex***" to the top.


```
    "import/first": "error",
    "import/no-duplicates": "error",
    "import/newline-after-import": "warn"

.......

        "simple-import-sort/imports": [
          "warn",
          {
            "groups": [
              // Vex goes first!
              ["^.*/vex$"],
              ["^.*/vexflow_test_helpers$"],
              // Side effect imports.
              ["^\\u0000"],
              // Packages.
              // Things that start with a letter (or digit or underscore), or `@` followed by a letter.
              ["^@?\\w"],
              // Absolute imports and other imports such as Vue-style `@/foo`.
              // Anything not matched in another group.
              ["^"],
              // All other relative imports (anything that starts with a dot).
              ["^\\."]
            ]
          }
```

**Pull request merged**
