### PR TITLE
generate map file in debug mode

### PR DESCRIPTION
**Pull request by AaronDavidNewman**
#794 Map file not generated for debug build

### CODE REVIEW

**Comment by 0xfe** [comment]
This disables map files for production, where it is more important (IMO). Is that intentional?

**Comment by AaronDavidNewman** [comment]
Hmm...a fair point.  So maybe we always want the map file, then?  Before, it was generating a map file for the minified version but not the debug version.  While it's possible to debug the monolith, it is not ideal

`devtool: 'source-map',...`

I think that's what it did prior to April.

**Comment by 0xfe** [comment]
How about an env setting for it instead,  e.g., calling `VEX_GENMAP=true grunt` will always generate a map file? So:

```
devtool: (process.env.VEX_GENMAP || mode === 'production') ? 'source-map' : false
```

**Comment by AaronDavidNewman** [comment]
OK.

**Comment by 0xfe** [comment]
Thanks Aaron. Can you confirm that this works correctly for:

- with env flag:
  + dev: generates source map
  + prod: generates source map
- without env flag
  + dev: does not generate source map
  + prod: generates source map

**Comment by AaronDavidNewman** [comment]
That is exactly how it works.

**Comment by 0xfe** [comment]
Thanks, merging.

**Pull request merged**
