### PR TITLE
Question: Remove assignment of `fillStyle` and `strokeStyle` in tests?

### PR DESCRIPTION
**Pull request by rvilarl**
addresses #1452 

A lot of minor visual differences. I will copy the bravura ones.

### CODE REVIEW

**Comment by rvilarl** [comment]
Annotation Bottom_Annotation Bravura
Annotation Bottom_Annotation Bravura_current
Annotation Bottom_Annotation Bravura_reference
Annotation Bottom_Annotations_with_Beams Bravura
Annotation Bottom_Annotations_with_Beams Bravura_current
Annotation Bottom_Annotations_with_Beams Bravura_reference
Annotation Fingerpicking Bravura
Annotation Fingerpicking Bravura_current
Annotation Fingerpicking Bravura_reference
Annotation Harmonics Bravura
Annotation Harmonics Bravura_current
Annotation Harmonics Bravura_reference
Annotation Placement Bravura
Annotation Placement Bravura_current
Annotation Placement Bravura_reference
Annotation Simple_Annotation Bravura
Annotation Simple_Annotation Bravura_current
Annotation Simple_Annotation Bravura_reference
Annotation Standard_Notation_Annotation Bravura
Annotation Standard_Notation_Annotation Bravura_current
Annotation Standard_Notation_Annotation Bravura_reference
Annotation Test_Justification_Annotation_Stem_Down Bravura
Annotation Test_Justification_Annotation_Stem_Down Bravura_current
Annotation Test_Justification_Annotation_Stem_Down Bravura_reference
Annotation Test_Justification_Annotation_Stem_Up Bravura
Annotation Test_Justification_Annotation_Stem_Up Bravura_current
Annotation Test_Justification_Annotation_Stem_Up Bravura_reference
Articulation Articulation___Vertical_Placement Bravura
Articulation Articulation___Vertical_Placement Bravura_current
Articulation Articulation___Vertical_Placement Bravura_reference
Bend Bend_Phrase Bravura
Bend Bend_Phrase Bravura_current
Bend Bend_Phrase Bravura_reference
Bend Double_Bends Bravura
Bend Double_Bends Bravura_current
Bend Double_Bends Bravura_reference
Bend Reverse_Bends Bravura
Bend Reverse_Bends Bravura_current
Bend Reverse_Bends Bravura_reference
ChordSymbol Bottom_Chord_Symbols Bravura
ChordSymbol Bottom_Chord_Symbols Bravura_current
ChordSymbol Bottom_Chord_Symbols Bravura_reference
ChordSymbol Bottom_Stem_Down_Chord_Symbols Bravura
ChordSymbol Bottom_Stem_Down_Chord_Symbols Bravura_current
ChordSymbol Bottom_Stem_Down_Chord_Symbols Bravura_reference
ChordSymbol Chord_Symbol_Font_Size_Tests Bravura
ChordSymbol Chord_Symbol_Font_Size_Tests Bravura_current
ChordSymbol Chord_Symbol_Font_Size_Tests Bravura_reference
ChordSymbol Chord_Symbol_Kerning_Tests Bravura
ChordSymbol Chord_Symbol_Kerning_Tests Bravura_current
ChordSymbol Chord_Symbol_Kerning_Tests Bravura_reference
ChordSymbol Chord_Symbol_With_Modifiers Bravura
ChordSymbol Chord_Symbol_With_Modifiers Bravura_current
ChordSymbol Chord_Symbol_With_Modifiers Bravura_reference
ChordSymbol Double_Bottom_Chord_Symbols Bravura
ChordSymbol Double_Bottom_Chord_Symbols Bravura_current
ChordSymbol Double_Bottom_Chord_Symbols Bravura_reference
ChordSymbol Top_Chord_Symbols Bravura
ChordSymbol Top_Chord_Symbols Bravura_current
ChordSymbol Top_Chord_Symbols Bravura_reference
ChordSymbol Top_Chord_Symbols_Justified Bravura
ChordSymbol Top_Chord_Symbols_Justified Bravura_current
ChordSymbol Top_Chord_Symbols_Justified Bravura_reference
Dot Basic Bravura
Dot Basic Bravura_current
Dot Basic Bravura_reference
Dot Multi_Voice Bravura
Dot Multi_Voice Bravura_current
Dot Multi_Voice Bravura_reference
NoteHead Basic Bravura
NoteHead Basic Bravura_current
NoteHead Basic Bravura_reference
NoteHead Bounding_Boxes Bravura
NoteHead Bounding_Boxes Bravura_current
NoteHead Bounding_Boxes Bravura_reference
Ornament Jazz_Ornaments Bravura
Ornament Jazz_Ornaments Bravura_current
Ornament Jazz_Ornaments Bravura_reference
Rests Auto_Align___Beamed_Notes_Stems_Down Bravura
Rests Auto_Align___Beamed_Notes_Stems_Down Bravura_current
Rests Auto_Align___Beamed_Notes_Stems_Down Bravura_reference
Rests Auto_Align___Beamed_Notes_Stems_Up Bravura
Rests Auto_Align___Beamed_Notes_Stems_Up Bravura_current
Rests Auto_Align___Beamed_Notes_Stems_Up Bravura_reference
Rests Auto_Align___Single_Voice__Align_All_ Bravura
Rests Auto_Align___Single_Voice__Align_All_ Bravura_current
Rests Auto_Align___Single_Voice__Align_All_ Bravura_reference
Rests Auto_Align___Single_Voice__Default_ Bravura
Rests Auto_Align___Single_Voice__Default_ Bravura_current
Rests Auto_Align___Single_Voice__Default_ Bravura_reference
Rests Auto_Align___Tuplets_Stems_Down Bravura
Rests Auto_Align___Tuplets_Stems_Down Bravura_current
Rests Auto_Align___Tuplets_Stems_Down Bravura_reference
Rests Auto_Align___Tuplets_Stems_Up Bravura
Rests Auto_Align___Tuplets_Stems_Up Bravura_current
Rests Auto_Align___Tuplets_Stems_Up Bravura_reference

**Comment by rvilarl** [comment]
I think it is not necessary to add the rest.
@ronyeh could you look into that? You made some changes on these lines.
Ready for review.

**Comment by rvilarl** [comment]
Why do I make this question/suggestion?

I think that manipulating the context directly in the tests provides results that my hide unexpected behaviour of the vanilla rendering.

@AaronDavidNewman @mscuthbert @sschmidTU what do you think?

**Comment by AaronDavidNewman** [comment]
I have no objections.

**Comment by rvilarl** [comment]
@AaronDavidNewman thanks!

**Pull request merged**
