### PR TITLE
Lint: tremolo, vex, voice

### PR DESCRIPTION
**Pull request by Silverwolf90**

### CODE REVIEW

**Comment by Silverwolf90** [comment]
Altered the visual regression script to always print output. But I don't know bash... so we'll see how it goes. :)

**Comment by Silverwolf90** [comment]
```
You have 0 warning(s):
You have 258 pass(es):
You have 0 fail(s):
```

**Comment by Silverwolf90** [comment]
whoops I guess I didn't think about force push removing comments

@0xfe script now simpler! shows message if no failures

**Comment by Silverwolf90** [comment]
```
...

Results stored in ./build/images/diff/results.txt
All images with a difference over threshold, 0.01, are
available in ./build/images/diff, sorted by perceptual hash.

Success - All diffs under threshold!


The command "npm test" exited with 0.

Done. Your build exited with 0.
```

**Comment by 0xfe** [comment]
Yes, this is better. Merging!

**Pull request merged**
