### PR TITLE
fix tabnotes stem length

### LINKED ISSUE #1285: Issues in tests/flow.html (3)
related to #941

**3. Stems too long in Tabnotes**
image

### PR DESCRIPTION
**Pull request by rvilarl**
fix #1285

Visual differences:

**Bravura Current**
TabNote TabNote_Stems_Up Bravura
TabNote TabNote_Stems_Down Bravura
**Bravura Reference**
TabNote TabNote_Stems_Up Bravura
TabNote TabNote_Stems_Down Bravura
**Gonville Current**
TabNote TabNote_Stems_Up Gonville
TabNote TabNote_Stems_Down Gonville
**Gonville Reference**
TabNote TabNote_Stems_Up Gonville
TabNote TabNote_Stems_Down Gonville
**Petaluma current**
TabNote TabNote_Stems_Up Petaluma
TabNote TabNote_Stems_Down Petaluma
**Petaluma Reference**
TabNote TabNote_Stems_Up Petaluma
TabNote TabNote_Stems_Down Petaluma

### CODE REVIEW

**Comment by rvilarl** [comment]
Tabnotes were missed when fixing the stem length of Stavenotes. Minor fix.
@0xfe ready to review

**Comment by 0xfe** [comment]
Looks good. Are there diffs on the beamed notes?

**Comment by rvilarl** [comment]
> Looks good. Are there diffs on the beamed notes?

The only diffs are the ones presented above.

**Comment by 0xfe** [comment]
Great, LGTM.

**Pull request merged**
