### PR TITLE
Put test declarations in a separate file

### PR DESCRIPTION
**Pull request by wassertim**

### CODE REVIEW

**Comment by rvilarl** [comment]
@wassertim I get: **Module not found: Error: Can't resolve './declarations' in '/home/rodrigo/git/vexflow/tests'**

**Comment by rvilarl** [comment]
@wassertim with this approach I got the same error I got with the following appoach in declarations.d.ts
```
export declare const QUnit: any;
export declare const ok: any;
export declare const test: any;
export declare const notOk: any;
export declare const notEqual: any;
export declare const strictEqual: any;
export declare const notStrictEqual: any;
export declare const deepEqual: any;
export declare const notDeepEqual: any;
```

**Comment by rvilarl** [comment]
@0xfe I have checked out this branch and it works properly. Please merge it and I will rebase and figure out my error :)

**Comment by rvilarl** [comment]
Difference found, I thought I had to use a .d.ts file and I created `declarations.d.ts` not `declarations.ts`

**Comment by 0xfe** [comment]
Excellent!

**Pull request merged**
