### PR TITLE
Typescript: typedoc documentation (proposal on #869)

### PR DESCRIPTION
**Pull request by rvilarl**
As suggested in #869.

I have created `./typedoc.ts` to put all the elements in a single module in order to facilitate the review activities during the migration. With this approach all the classes, interfaces & type aliases are accesible  in a single page under `exports`.

### CODE REVIEW

**Comment by rvilarl** [comment]
@0xfe do you find this documentation approach of interest? As I said I believe it should help as minimum with the reviews. But I think that it the answer to many comments on lack of API documentation.

**Comment by 0xfe** [comment]
This is fine with me. I'm okay with removing `docco` too. Let's do that in a separate PR.

**Comment by rvilarl** [comment]
@0xfe if this is fine you can simply merge this PR. We will remove `docco`in a separate PR but I suggest we wait until the migration is over. Typedoc only documents the migrated files.

**Comment by 0xfe** [comment]
Okay, looks good. Merging. Thanks!

**Pull request merged**
