### PR TITLE
Refactor FontMetrics

### LINKED ISSUE #1485: Refactor FontMetrics
FontMetrics has two issues that I would like to resolve:
- the  different values are not consistenly located inside or outside the glyphs section.
- a lot of `any`

I will submit a PR including all the changes and smaller PRs (part of the previous one to facilitate the review)

### PR DESCRIPTION
**Pull request by rvilarl**
fix  #1485

### CODE REVIEW

**Comment by rvilarl** [comment]
@AaronDavidNewman @mscuthbert @ronyeh @sschmidTU **any objection to merge this one?** 
It removes a lot of `any` and rationalises the metric files.
I started dividing it in smaller chunks: #1487 is now merged and #1488 is open. I just thougth it might be better to go for the whole lot.
There are no visual differences.

**Comment by sschmidTU** [comment]
No objections, especially since there are no visual differences!

**Review by AaronDavidNewman — APPROVED** [review]
lgtm

**Comment by rvilarl** [comment]
@AaronDavidNewman thanks!

**Pull request merged**
