### PR TITLE
custom noteheads refactored

### LINKED ISSUE #1415: Fix stems + noteheads
https://github.com/0xfe/vexflow/pull/1401#issuecomment-1163651219

Recent PRs have caused some stems to be detached from the noteheads. We need to update the metrics files (esp for Leland) so that the stems and noteheads connect smoothly.

### PR DESCRIPTION
**Pull request by rvilarl**
fixes #1415 
location is now calculated on run time and the associated metrics are no longer required.

### CODE REVIEW

**Comment by rvilarl** [comment]
Current results with all fonts:

pptr-NoteHead Drum_Chord_Heads Bravura svg
pptr-NoteHead Drum_Chord_Heads Gonville svg
pptr-NoteHead Drum_Chord_Heads Leland svg
pptr-NoteHead Drum_Chord_Heads Petaluma svg
pptr-NoteHead Various_Heads Bravura svg
pptr-NoteHead Various_Heads Gonville svg
pptr-NoteHead Various_Heads Leland svg
pptr-NoteHead Various_Heads Petaluma svg
pptr-NoteHead Various_Note_Heads_1 Bravura svg
pptr-NoteHead Various_Note_Heads_1 Gonville svg
pptr-NoteHead Various_Note_Heads_1 Leland svg
pptr-NoteHead Various_Note_Heads_1 Petaluma svg
pptr-NoteHead Various_Note_Heads_2 Bravura svg
pptr-NoteHead Various_Note_Heads_2 Gonville svg
pptr-NoteHead Various_Note_Heads_2 Leland svg
pptr-NoteHead Various_Note_Heads_2 Petaluma svg

**Comment by AaronDavidNewman** [comment]
I don't see any difference in output at all - that's the intent?  The code looks good to me.

**Review by AaronDavidNewman — APPROVED** [review]
I don't see any output difference.

**Comment by rvilarl** [comment]
Thanks for the review!

**Comment by ronyeh** [comment]
Does this have any impact on performance or other tests? I'm about to test and release 4.1 so I'm naturally hesitant to include last minute merges. But if you both are comfortable, we can push 4.1 and worst case if anything comes up, 4.1.1.... 😁

**Pull request merged**
