### PR TITLE
fixes `getTieEndX` in `Stave` (StaveModifiers placed at the end of the Stave collide with StaveTies without end notes.)

### LINKED ISSUE #489: StaveModifiers placed at the end of the Stave collide with StaveTies without end notes.
See the collision at the end of the stave in this example:

image

StaveModifiers placed at the beginning do *not* exhibit this issue (although the spacing leaves something to be desired):

image

### PR DESCRIPTION
**Pull request by rvilarl**
Fixes #489

**StaveTie › No End Note** 

before:
StaveTie No_End_Note Petaluma_Reference

after:
StaveTie No_End_Note Petaluma_Current

No other visual difference

### CODE REVIEW

**Comment by 0xfe** [comment]
Thanks Rodrigo. Does this change anything if there's no stave end modifier? Does the tie still reach the end of the stave?

**Comment by rvilarl** [comment]
It does not produce any other visual change. Is there already a test for what you refer to? I am not sure that I really understand the case.

**Comment by 0xfe** [comment]
Is there a test where the Tie begins on the last note and there's nothing on the right? (That's what the 'No End Note' test should have been, but it seems like it now ends with a stave modifier.) In that case, the tie should hit the right stave barline.

**Comment by rvilarl** [comment]
@0xfe I have added two tests related to cases without note and without Clef both at start and at end.

I believe that the output is correct:

image

image

image

image

**Comment by rvilarl** [comment]
@0xfe hopefully ready to merge

**Comment by 0xfe** [comment]
Looks great, thanks for adding those tests!

**Pull request merged**
