### PR TITLE
Fix/1523/bravura leland petaluma

### PR DESCRIPTION
**Pull request by rvilarl**
Now rebased to master

### CODE REVIEW

**Comment by rvilarl** [comment]
@ronyeh in the force push above you can see that I only removed the changes in this PR. No change was lost, even the direct pushes to master.

**Comment by rvilarl** [comment]
Differences in Bravura:

1) The difference below is expected because the test changes the font to Petaluma
`Font Set_Music_Font_to_Petaluma Bravura`
**reference**
pptr-Font Set_Music_Font_to_Petaluma Bravura svg_reference
**current**
pptr-Font Set_Music_Font_to_Petaluma Bravura svg_current
2) The difference below is due to the fact that multimeasure uses TimeSignatures to draw the numbers
**reference**
pptr-MultiMeasureRest Simple_Test Bravura svg_reference
**current**
pptr-MultiMeasureRest Simple_Test Bravura svg_current

**Comment by rvilarl** [comment]
Differences in Leland:

1) The difference below is expected because the test changes the font to Petaluma
`Font Set_Music_Font_to_Petaluma Leland`
**reference**
pptr-Font Set_Music_Font_to_Petaluma Leland svg_reference
**current**
pptr-Font Set_Music_Font_to_Petaluma Leland svg_current

**Comment by rvilarl** [comment]
@ronyeh do you get now the same differences?

**Comment by ronyeh** [comment]
It looks OK now. Here's what I did:

## 0xfe Head Revision

```
git clone git@github.com:0xfe/vexflow.git .

git show --summary
	commit 5a2bbb0dd9cc10bc04492fa910d685578550ec14 (HEAD -> master, origin/master, origin/HEAD)
	Author: Ron B. Yeh <ronyeh@gmail.com>
	Date:   Thu Mar 2 12:43:22 2023 -0800

	    Update docs/api/.

npm ci

grunt

grunt generate:current

ls build/images/current/ | wc -l
	3857

```


## Rodrigo's PR

```
git clone https://github.com/rvilarl/vexflow.git .



git checkout fix/1523/bravuraLelandPetaluma
	branch 'fix/1523/bravuraLelandPetaluma' set up to track 'origin/fix/1523/bravuraLelandPetaluma'.
	Switched to a new branch 'fix/1523/bravuraLelandPetaluma'

npm ci

grunt

grunt generate:current

ls build/images/current/ | wc -l
    3857

```

I uploaded all image files to a test server, and used my image comparison tool to look for differences.

I get the same ones that you get. Here are some examples:

*0xfe* head revision on top, and *rvilarl* PR version on the bottom.
Open each image in different tabs and switch between the tabs.

https://test-c72s.onrender.com/0xfe/pptr-Tuplet.Single_Tuplets.Petaluma.svg
https://test-c72s.onrender.com/rvilarl/pptr-Tuplet.Single_Tuplets.Petaluma.svg

https://test-c72s.onrender.com/0xfe/pptr-canvas_MultiMeasureRest.Simple_Test.Bravura.png
https://test-c72s.onrender.com/rvilarl/pptr-canvas_MultiMeasureRest.Simple_Test.Bravura.png

What are we going to do with the multi measure differences?

What about the instances where the Petaluma numbers are now bigger (e.g., on top of triplet brackets). Do we need to reposition them to avoid the brackets and other symbols?

**Comment by ronyeh** [comment]
Looks OK to me. Let's continue to fix some of the smaller issues with Petaluma and maybe figure out a good solution for the multimeasure rests.

**Comment by rvilarl** [comment]
@ronyeh in your comparison tool it would help, I believe:
- to have a button to filter the files with changes only
- to have a different colour for the stack representation. Gray is dificult to see.

Thanks for reviewing this PR!

**Pull request merged**
