### PR TITLE
Support missing accidental glyphs

### PR DESCRIPTION
**Pull request by infojunkie**
As per #318.

### CODE REVIEW

**Comment by 0xfe** [comment]
Thanks for the change, Karim. Can you remove the releases and the `{component|package}.json` files from this PR? Those are for me to update and push. :-)

**Comment by infojunkie** [comment]
Reverted the files you specified - hope I did it right :-)

**Comment by SalahAdDin** [comment]
:+1:

**Comment by 0xfe** [comment]
Good job. Merged. Thanks!

**Pull request merged**
