### PR TITLE
Add shortcut to `Factory` constructor.

### PR DESCRIPTION
**Pull request by 0xfe**
This makes the common case of just setting a DOM selector more elegant. @Silverwolf90 let me know what you think of this. (I'm in two minds about it.)

### CODE REVIEW

**Comment by Silverwolf90** [comment]
I don't have a particularly strong opinion -- but it feels a bit premature. Is such minimal configuration the common case?

**Comment by 0xfe** [comment]
Drat, I read your previous 'sounds fine to me reply' (on e-mail) and assumed it was for this PR! woops!

**Comment by 0xfe** [comment]
To answer your question, I was writing up a tutorial for EasyScore, and most of the examples started like this:

```javascript
vf = new VF.Factory({renderer: {selector: 'boo'}})
```

...which got annoying after a while. (I don't know if this really will be the common case in general, but it was for me :-)

**Comment by Silverwolf90** [comment]
What about relying on static methods instead of polymorphic constructors?

```javascript
vf = VF.Factory.fromSelector(selector)
```

Dunno. Just an idea, don't feel strongly either way!

**Comment by 0xfe** [comment]
Yeah, I think that's a better idea. I'll fix master.

**Pull request merged**
