### PR TITLE
Change percussion cross note head glyph

### PR DESCRIPTION
**Pull request by PieterHartzer**
Changed the glyph for the cymbals from a double sharp to a cross.
Included the /diff folder as specified on the [Wiki](https://github.com/0xfe/vexflow/wiki/Visual-Regression-Tests).  (Is this the correct way?)

Before:
image

After:
image

### CODE REVIEW

**Comment by 0xfe** [comment]
Thanks for the commit. Looks good to me, however can you remove the `.png` files please? (The new tests verify against the last package version.)

**Comment by PieterHartzer** [comment]
@0xfe `.png` files are now gone.

**Comment by 0xfe** [comment]
Thanks, merged. I think that stem extension still needs fixing.

**Comment by PieterHartzer** [comment]
@0xfe I am on it.  I just messed up my repo and is fixing that then I will get on the stem extension issue.  Thanks for merging this in.

**Pull request merged**
