### PR TITLE
npm-upgrade & docco dependency removed

### LINKED ISSUE #1235: TypeDoc issues with HTML tags in the comments
S 2021-11-20 at 10 30 22

The above issue is in `vexflow/docs/api/classes/CanvasContext.html#canvas` although I'm sure it shows up in other files as well.

Scroll down to the **canvas** property and it looks like the comment is broken. If you use the dev tools dom inspector, you'll see that there is a random canvas element inside the comment.

DOM:
```
<p>The HTMLCanvasElement or OffscreenCanvas that is associated with the above context.
If there was no associated <canvas> element, just store the default WIDTH / HEIGHT.</canvas></p>
```

Our canvascontext.ts source file looks like:
```
  /**
   * The HTMLCanvasElement or OffscreenCanvas that is associated with the above context.
   * If there was no associated <canvas> element, just store the default WIDTH / HEIGHT.
   */
  canvas: HTMLCanvasElement | OffscreenCanvas | { width: number; height: number };
```

So it looks like typedoc isn't escaping these tags properly. It looks like typedoc is using markdown parsing for the comments, so an HTML tag will be sent straight to the final output. I guess we need to be using single backticks to make sure the code is rendered properly.

```
`<canvas>`
```

@rvilarl at some point we should review our typedoc generated documentation to see if there are any other issues like this. I can fix this one instance in my next PR.

### PR DESCRIPTION
**Pull request by rvilarl**
TypeScript 4.5.2 is now released, no need to stay with the release candiate.

No visual differences.
Fixes #1235

### CODE REVIEW

**Comment by 0xfe** [comment]
Conflicts.

**Comment by rvilarl** [comment]
Conflicts resolved.
@0xfe ready to merge

**Comment by rvilarl** [comment]
@0xfe I have included #1237 changes here on the last two commits.
- `png treated as binary, typedoc generates in docs/api` is the change.
- `documentation automatic update` is generated from typedoc, no need to review.

@0xfe I think ready to merge

**Comment by 0xfe** [comment]
lgtm

**Pull request merged**
