### PR TITLE
Vibrato spanning over multiple notes

### PR DESCRIPTION
**Pull request by bforian**
Implements a new class, called VibratoBracket, that is capable of rendering vibrato effect over multiple notes. The class structure is similar to the TextBracket class and uses the rendering function of the Vibrato class.

### CODE REVIEW

**Comment by bforian** [comment]
vibrato-bracket-simple
vibrato-bracket-no-start
vibrato-bracket-no-end

**Comment by 0xfe** [comment]
Thanks @bforian. This looks like it breaks the build because of lint errors. Can you fix?

**Comment by bforian** [comment]
Fixed, thanks for noticing!

**Comment by 0xfe** [comment]
Looks good @bforian. Merged. Thanks!

**Comment by bforian** [comment]
Awesome, thanks!

**Pull request merged**
