### PR TITLE
Fix two voice note formatting

### PR DESCRIPTION
**Pull request by Silverwolf90**
image

The bug is that `keyProps.line` and `stave.getYForLine()` are incompatible -- so we have to convert `keyProps.line`. I wrote about this in the ["Development Gotchas"](https://github.com/0xfe/vexflow/wiki/Development-Gotchas) wiki page.

Worth a look at the diffs.

### CODE REVIEW

**Comment by 0xfe** [comment]
Thanks. That's pretty ugly. :-/

**Comment by 0xfe** [comment]
Looks like this causes some aligned stave notes (even across staves) to get shifted.

See last two notes below:

screen shot 2016-08-21 at 6 07 37 pm

And last two notes on first two staves below:

screen shot 2016-08-21 at 6 09 40 pm

**Comment by Silverwolf90** [comment]
Fixed.

**Comment by 0xfe** [comment]
Still some off alignment in tests:

### Current (Formatter - StaveNote Justification)
screen shot 2016-08-21 at 8 48 56 pm

### Blessed (Formatter - StaveNote Justification)
screen shot 2016-08-21 at 8 48 50 pm

### Current (NoteSubGroup - MultiStaff)
screen shot 2016-08-21 at 8 48 30 pm

### Blessed (NoteSubGroup - MultiStaff)
screen shot 2016-08-21 at 8 48 20 pm

**Comment by Silverwolf90** [comment]
(The names of the tests are flipped) 

The StaveNote justification tests was a silly mistake, used `<=` instead of `<`.

But the `NoteSubGroup` tests , and previous `Formatter - Multiple Staves No Justification` diffs are related to `.joinVoices` being used to join all formatted voices, instead of only voices on the same stave. 

`.joinVoices` has been a source of confusion for lots of people over many years -- we should probably reconsider this part of the API and make the construction of `ModifierContexts` easier to understand. The fact that this is leaking into the tests shows that even with review, improper usage is difficult to spot.

**Comment by 0xfe** [comment]
Thanks Cyril -- I'm running the visual tests now. Re: `joinVoices`, hopefully the `System` class will take care of most of the common cases, and users will never have to see `joinVoices` again.

**Comment by 0xfe** [comment]
All good. Merging. Thanks for tracking this down!

**Pull request closed without merging**
