### PR TITLE
Remove hardcoded accidental metrics

### PR DESCRIPTION
**Pull request by Silverwolf90**
Removes hardcoded glyph metrics in `tables.js`. Lots of small diffs are expected.

Working towards https://github.com/0xfe/vexflow/issues/349

### CODE REVIEW

**Comment by 0xfe** [comment]
Looks good. Lots of visual diffs.

One noticeable regression is with cautionary accidentals, where the glyph isn't centered between the parenthesis.

screen shot 2016-09-04 at 12 00 43 pm

**Comment by Silverwolf90** [comment]
It's better now, since the double sharp looks good. I suspect the bounding boxes for the flat aren't perfect because they still look like there's too much padding on the right. This might not be fixable until SMuFL support.

**Comment by Silverwolf90** [comment]
image

**Comment by 0xfe** [comment]
How hard would it be to add a shift to the flats? They do kinda look off.

**Comment by Silverwolf90** [comment]
Not hard, just gross. Basically have to reinstate hardcoded constants per accidental.

**Comment by 0xfe** [comment]
Yes, gross I agree, but with these changes, less gross than before. We only need shift values for the flats in `accidentalCodes`. (It sucks, but that's our burden, not the user's.)

**Comment by mscuthbert** [comment]
If it's a consolation, eventually flats will need to be a special case in bounding box specification anyhow since the stem of a flat or double flat is the only musical character that a slur is allowed to intersect with (under normal circumstances).  So you can be content that special flat bounding box adjustments were going to be inevitable eventually anyhow.  :-)

**Comment by Silverwolf90** [comment]
Fixed. Added a shift to pretty much all accidentals so symmetrical left/right padding (ie: identical values) produces symmetrical results.

image

@mscuthbert Good point! But that information is ideally extracted from `SMuFL` metadata, in your example, [the `accidentalFlat` glyph has a cutout that provides this y coordinate (in staff spaces) without us having to store it.](http://w3c.github.io/smufl/gitbook/specification/bbox-cut-outs.html)

**Comment by 0xfe** [comment]
Looks good. Merging.

**Pull request merged**
