### PR TITLE
KeySignature.cancelKey - Check if accList[0] exists before accessing it

### PR DESCRIPTION
**Pull request by vinzentt**
fixes https://github.com/0xfe/vexflow/issues/335

### CODE REVIEW

**Comment by 0xfe** [comment]
Thanks for the fix @vinzentt. Can you please remove `releases/*` from this PR?

**Comment by vinzentt** [comment]
Done. I was not sure if the release folder was needed.
Maybe a branch devel or ci for the PR would be more clear.

**Comment by vinzentt** [comment]
I added a fix to throw an error when instantiating a tuplet without notes. 
It was because new Array() !== [].

**Comment by 0xfe** [comment]
Thanks @vinzentt. Will merge.

(Also, not sure that I understood your comment about "branch devel or ci".)

**Comment by vinzentt** [comment]
(just an idea. If you create a branch called develop or ci, and ask users to do their pull requests on it, it will be more clear where to make the PR and how to make it (no release file needed on a ci branch). 
This way, you can add the release files only when merging on master, and you can merge the pull requests right away without waiting for a release. Just following this model http://nvie.com/files/Git-branching-model.pdf)

**Comment by panarch** [comment]
@vinzentt It looks not reasonable for vexflow project, because vexflow requires release files to run test. It generates blessed images from release files and current images from current build, so release files are necessary for this process. So ci cannot work without release files.

**Comment by 0xfe** [comment]
Thanks @vinzentt. Merged!

**Pull request merged**
