### PR TITLE
Update package.json and package-lock.json

### PR DESCRIPTION
**Pull request by ronyeh**
Inspired by comment https://github.com/0xfe/vexflow/issues/1130#issuecomment-913042958 to bump the versions on our main tools.

Update versions:
- typescript => 4.4.2
- typedoc => 0.21.9
- webpack => 5.52.0
- eslint-plugin-prettier => 4.0.0
- @typescript-eslint/eslint-plugin => 4.31.0
- @typescript-eslint/parser => 4.31.0

Remove jQuery. We have a local version and do not need it in node_modules.
Remove browserify. We do not seem to use it anymore.

I ran `npm run test:reference` and also `flow.html` and everything seems to be fine. :-)

### CODE REVIEW

**Comment by rvilarl** [comment]
@roney do you use `npm-upgrade`? 
Some suggested updates are missing:
```
  eslint-plugin-import               ^2.23.4   →   ^2.24.2 
  grunt                              ^1.0.4    →    ^1.4.1 
  grunt-git                          ^1.0.14   →    ^1.1.1 
  jsdom                              ^16.7.0   →   ^17.0.0 
  npm                                ^7.20.3   →   ^7.22.0 
  webpack-dev-server                 ^3.11.2   →    ^4.1.1 
```

**Comment by ronyeh** [comment]
Ah, I did not! I manually updated package.json for each tool that I wanted to modify. I didn't want to do a mass upgrade in case something went wrong.

But if you recommend, I can also npm-upgrade the packages you listed.

**Comment by 0xfe** [comment]
Please see https://github.com/0xfe/vexflow/wiki/Build-And-Release-Instructions#upgrading-dependencies for my process. Feel free to evolve that process.

**Comment by ronyeh** [comment]
> Please see https://github.com/0xfe/vexflow/wiki/Build-And-Release-Instructions#upgrading-dependencies for my process. Feel free to evolve that process.

`npm cache clean`

Current version of npm claims that this is no longer necessary. :-) Should we remove it from your process?

```
npm ERR! As of npm@5, the npm cache self-heals from corruption issues
npm ERR! by treating integrity mismatches as cache misses.  As a result,
npm ERR! data extracted from the cache is guaranteed to be valid.  If you
npm ERR! want to make sure everything is consistent, use `npm cache verify`
npm ERR! instead.  Deleting the cache can only make npm go slower, and is
npm ERR! not likely to correct any problems you may be encountering!
```

**Review by rvilarl — APPROVED** [review]

**Comment by rvilarl** [comment]
> Ah, I did not! I manually updated package.json for each tool that I wanted to upgrade. I didn't want to do a mass upgrade in case something went wrong.
> 
> But if you recommend, I can also npm-upgrade the packages you listed.

Sorry for the late reply. Yes that was my recommendation.

**Comment by rvilarl** [comment]
> > Please see https://github.com/0xfe/vexflow/wiki/Build-And-Release-Instructions#upgrading-dependencies for my process. Feel free to evolve that process.
> 
> `npm cache clean`
> 
> Current version of npm claims that this is no longer necessary. :-) Should we remove it from your process?
> 

I would remove `npm cache clean`. `npm-check-updates` and `npm-upgrade` produce the same recommendation. The difference is that the second one allows you to leave packages untouched. This was good until the last time I used it because grunt-git was outdated and grunt had to be left in version 1.0.4 to be compatible.

**Comment by ronyeh** [comment]
No worries about the late reply! We're all in different time zones, so it's kind of fun to see your messages late at night and Mohit's notifications early in the morning. It's like a play-by-mail board game.

**Comment by ronyeh** [comment]
**Summary:** I upgraded all the packages via Mohit's method. Removed a few packages that do not seem to be used. I tested with `grunt watch` and `npm run test:reference` and everything seems to be fine.

---
### On removing `webpack-dev-server`:

Are any of us using `webpack-dev-server`? After the npm-check-updates, webpack-dev-server was upgraded to 4.1.1.

However, grunt seems to use a private module that is no longer in recent versions of webpack-dev-server. 

```
Error: Cannot find module 'webpack-dev-server/lib/util/createDomain'
>> Require stack:
>> - vexflow/node_modules/grunt-webpack/tasks/webpack-dev-server.js
>> - vexflow/node_modules/grunt/lib/grunt/task.js
>> - vexflow/node_modules/grunt/lib/grunt.js
>> - vexflow/node_modules/grunt-cli/bin/grunt
>> - vexflow/node_modules/grunt/bin/grunt
```

See: https://github.com/webpack/webpack-dev-server/issues/1483

And if you look at the current homepage of grunt-webpack, it says:

`Version 3.2.0 of webpack-dev-server is needed if used.`

So previously we were on 3.11.2. I upgraded to 4.1.1 and an error appears while building, but it doesn't break the build (everything finishes as usual). However, we don't seem to be using it, so I decided to remove `webpack-dev-server`.

**Comment by ronyeh** [comment]
I think this one's ready. Worst case, we can revert one of the libraries if needed.

**Comment by 0xfe** [comment]
@ronyeh @rvilarl I'm in no way wed to that upgrade process, so feel free update the wiki if there's a better way (which you agree on, ofcourse.) If the process allows you to upgrade incrementally, is testable, and lets you dry run, then that works for me.

**Comment by 0xfe** [comment]
Also, LGTM! :-)

**Pull request merged**
