### PR TITLE
Suggested addition for a dynamic code base

### PR DESCRIPTION
**Pull request by spianoDev**
I have made an additional ReadMe for anyone who wants to use the code on a note by note basis.

### CODE REVIEW

**Comment by spianoDev** [comment]
> Looks like a nice quickstart guide!
> 
> However, a .md file in the main directory is probably not the best way to go place it There aren't many files in the main directory and for .mds, the Readme is the only one.
> And if we had a .md file for every Wiki page, the main directory would be flooded.
> https://github.com/0xfe/vexflow
> 
> Why not write a Wiki entry instead?
> https://github.com/0xfe/vexflow/wiki
> Not sure if you have permissions though.

Thank you for suggestion... I will look into that this weekend!

**Comment by 0xfe** [comment]
Thanks for reviewing @sschmidTU.

@spianoDev, the Wiki is publicly editable, feel free to add a new page. :-)

**Comment by mix3d** [comment]
I don't understand why you `npm install vexflow` but then just use the unpkg import in the html. Seems redundant.

**Comment by spianoDev** [comment]
> I don't understand why you `npm install vexflow` but then just use the unpkg import in the html. Seems redundant.

When I tried to run the program without the html script, I was getting an error message referring to the VexFlow Factory. Adding the script cleared that error and allowed the project to render the score.

**Comment by mix3d** [comment]
>When I tried to run the program without the html script, I was getting an error message referring to the VexFlow Factory. Adding the script cleared that error and allowed the project to render the score.

Right, but if you `npm uninstall vexflow` you'll have the same result. The `npm install` isn't doing anything in your example. 

Really, vexflow needs an ESM compatible build, to use instead of one that pollutes the global namespace; many linters and bundlers do not like this.

I've found a workaround by importing the code directly (see below), but this is far from ideal. The NPM module is not using the `.npmignore` file to simplify what's in the module: https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package
 
Example:
```
import Vex from 'vexflow/src/index.js'
const VF = Vex.Flow

... etc
```

**Comment by spianoDev** [comment]
> Right, but if you `npm uninstall vexflow` you'll have the same result. The `npm install` isn't doing anything in your example, and is misleading.

I will have to play with it again to see if that is true. I cannot remember if I installed globally (I suspect not) or locally in the specific repo I was building. My current schedule is a bit nutty, so it will likely be another couple of weeks before I can dig back into this project. Thanks for commenting!

**Comment by spianoDev** [comment]
I submitted to the wiki... please feel free to message me with any edits or improvements!

**Pull request closed without merging**
