### PR TITLE
Secondary breaks/partial beam fixes

### PR DESCRIPTION
**Pull request by aaronmars**
This fixes an edge case where partial beams were not pointing the correct direction when the secondary beam was being broken manually with `Beam.breakSecondaryAt()` (as reported in https://github.com/0xfe/vexflow/issues/302).

The fix required a re-write of `Beam.getBeamLines()`.

I also took the liberty of adding a new option to `Beam.generateBeams()` called `secondary_breaks `.  This parameter will force secondary breaks to be auto-applied per beam group, rather than relying on breakSecondaryAt() for each case.

### CODE REVIEW

**Comment by 0xfe** [comment]
Thanks for the change. This conflicts with your "flat beams" changes. Can you resolve?

**Comment by aaronmars** [comment]
Resolved.

**Comment by aaronmars** [comment]
OK.  The conflicts have been merged, and I had to do an extra commit to remove some temp files that were accidentally added by my merge tool.

**Comment by 0xfe** [comment]
Great! Thanks.

**Pull request merged**
