### PR TITLE
Standardize `CATEGORY` property.

### PR DESCRIPTION
**Pull request by ronyeh**
Standardize `CATEGORY` / `getCategory()` / `this.setAttribute('type', ...)`.
The string is now always UpperCamelCaseSingular.
Improve the typeguard functions to check for the `CATEGORY` property directly.
Element's `this.attrs.type` is set to `this.getCategory()` in the `Element` constructor.

Fixes https://github.com/0xfe/vexflow/issues/1107

### CODE REVIEW

**Comment by ronyeh** [comment]
Now there is a single `getCategory()` function (in the `Element`) class. Any descendant of Element inherits this method, and only needs to provide its own static `CATEGORY` property. The isCategory() typeguard utility method has been refactored to look for `CATEGORY`.

```
  getCategory(): string {
    return (<typeof Element>this.constructor).CATEGORY;
  }

```

**Comment by ronyeh** [comment]
@mscuthbert if you have time next week, can you help review the new implementation of `isCategory()` in typeguard.ts?

https://github.com/0xfe/vexflow/pull/1138/files#diff-b4e62682a03cf67278ca1b02054f986cd7eccdf0b25ee5bf1f5bda7bbeea1dcaR36-R74

The overall idea is from now on, any object that wants to masquerade as a VexFlow class will need to declare a matching `static CATEGORY` property. For example:

```
  class FakeStaveNote {
    static CATEGORY = 'StaveNote';
    ...
  }
```

Additionally, I was able to remove all of the individual `getCategory()` methods, and declare it only in the `Element` class. The implementation is to return the static CATEGORY property, which is now always UpperCamelCaseSingular:
```
  /** Get element category string. */
  getCategory(): string {
    return (<typeof Element>this.constructor).CATEGORY;
  }
```

**Comment by ronyeh** [comment]
**This one's good to go.** 

No visual diffs relative to the current master @ 46e4cac2f4bc92a576f38b58f660a4e7d9ebaa98

There is now only one getCategory() function, in Element:
https://github.com/ronyeh/vexflow/blob/e2e7c5d76f954e4dd28881f24cd3493e4597ad5c/src/element.ts#L72-L75

Every descendant of Element that had a getCategory() now only has a static CATEGORY property. The property has been standardized to always be singular, and UpperCamelCase.

The `isCategory()` type check method has been updated to look for the static `CATEGORY` property directly. Previously it called the `getCategory()` method. Since this feature has been in VexFlow for only about a month, it seems low risk to change it. :-} Hopefully we won't need to change this any more.

See: https://github.com/ronyeh/vexflow/blob/category/src/typeguard.ts

**Comment by 0xfe** [comment]
Looks good overall. Would love to rethink this in the new typescript world. Having a CATEGORY is important for inventory management, but we could potentially also add interfaces for where they're used for their behaviours, so we get compile-time checking.

**Pull request merged**
