### PR TITLE
SVG Context

### PR DESCRIPTION
**Pull request by gristow**
Fixes issue #277 - Create SVGContext
- Implements new SVGContext using native SVG, rather than an external SVG library.
- Rewrites test helpers to run tests on specified backends.
- Deprecates RaphaelContext. (Noted in code; no warnings thrown at runtime.)

### CODE REVIEW

**Comment by 0xfe** [comment]
Thanks for the change, and for updating all the tests. Can you list the browsers you tested this on?

**Comment by gristow** [comment]
Yes, sure.

On OSX:
Chrome 39
Firefox 34
Safari 7.1.2
Opera 26

On iOS:
Safari 7.1 & 8.0
Chrome 39

I don't have easy access to a PC or Android device -- would be great if someone could check in IE...

Greg

**Comment by 0xfe** [comment]
I can verify Android and Linux (Chrome, Firefox). @mscuthbert or @Silverwolf90, do either of you have access to IE?

**Comment by Silverwolf90** [comment]
Just looked at it through IE 11.0.9600 and it looks great for the most part!

It seems that stave line thickness is not completely consistent, my hunch is that this is a scaling/anti-aliasing issue, and very possibly unavoidable. But it causes the barlines to ever so slighly protrude through the top and bottom lines in some cases.

image

Also text brackets seem to render sighly oddly.

image

image

**Comment by gristow** [comment]
@Silverwolf90
Thanks, Cyril -- can you check it again now?

I've got access to a Windows VM, so I've been able to do some testing on the text brackets issue.  The problem relates to ie's calculations of text width & height in SVG's using getBBox().  (It shows up in RaphaelContext as an issue, too.  We just hadn't previously been running the textbracket tests in Raphael.)

I implemented a polyfill for IE in the latest version, and the tests [are available here](http://www.gregoryristow.com/vex/flow/tests.html).

Gory details:
IE way over-pads text in italics -- fortunately it's a linear formula that was easy enough to derive after I ran tests across various text lengths, styles & font sizes:
ie's overestimate (in pixels) = FontSize(in pt) * 1.196 + 1.96

**Comment by gristow** [comment]
FYI -- here's what IE rendering now looks like on my Windows VM:
win8 1_ie_11 0

**Comment by gristow** [comment]
By the way, had a chance to test this on IE 11 in Windows 7 -- all tests are passing, and the text bracket issue seems to be fixed.  See attached screen shots.
text bracket
tests header

**Comment by 0xfe** [comment]
Thanks for the update. I tested this on Linux (FF/Chrome) as well, and all
looks good. Will merge.

On Sat, Jan 17, 2015 at 2:35 PM, Gregory Ristow <notifications@github.com>
wrote:

> By the way, had a chance to test this on IE 11 in Windows 7 -- all tests
> are passing, and the text bracket issue seems to be fixed. See attached
> screen shots.
> [image: text bracket]
> <https://cloud.githubusercontent.com/assets/8905340/5790072/0d53df30-9e56-11e4-8e65-7cdc47537e00.JPG>
> [image: tests header]
> <https://cloud.githubusercontent.com/assets/8905340/5790074/0ecf7298-9e56-11e4-9cb3-e3faa0de1dcf.JPG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vexflow/pull/278#issuecomment-70380935>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by gristow** [comment]
If you want to wait a few hours, I can tidy up some comments in there first so it looks better!

**Comment by 0xfe** [comment]
Yes, of course. I'm out of town right now anyway, so will merge on Monday.
:-)

On Sat, Jan 17, 2015 at 2:48 PM, Gregory Ristow <notifications@github.com>
wrote:

> If you want to wait a few hours, I can tidy up some comments in there
> first so it looks better!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vexflow/pull/278#issuecomment-70381449>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by gristow** [comment]
Ok -- if this looks good to you, Mohit, I think it's ready to merge.  (Test version [is available here](http://www.gregoryristow.com/vex/tests/flow.html).)

By the way, if you look at the dev console, you'll see a few errors being thrown.  I've tracked these down to bugs in TabNote calling context.lineTo() with an undefined y, and slashed grace notes (calling lineTo() without first calling moveTo() to set a pen location).  I can open issues for these if you want... they're probably easy fixes...

**Comment by 0xfe** [comment]
On Sun, Jan 18, 2015 at 1:42 AM, Gregory Ristow <notifications@github.com>
wrote:

> Ok -- if this looks good to you, Mohit, I think it's ready to merge. (Test
> version is available here
> <http://www.gregoryristow.com/vex/tests/flow.html>.)
>
Thanks! Will do.

> By the way, if you look at the dev console, you'll see a few errors being
> thrown. I've tracked these down to bugs in TabNote calling context.lineTo()
> with an undefined y, and slashed grace notes (calling lineTo() without
> first calling moveTo() to set a pen location). I can open issues for these
> if you want... they're probably easy fixes...
>
If you don't mind, please open an issue with the root cause that you found
(so I don't have to debug it again :-)

Thanks again.

—
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vexflow/pull/278#issuecomment-70398419>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by 0xfe** [comment]
Excellent change. Merged. Thanks a lot for working on this!

**Pull request closed without merging**
