### PR TITLE
Run automatic transforms on entire codebase

### PR DESCRIPTION
**Pull request by Silverwolf90**
Results of running `lebab` safe transforms and `eslint --fix`

The basic summary of the transforms:

* var -> const/let
* anonymous functions -> arrow functions
* shorthand object properties
* minor spacing tweaks
* some indentation fixes
* double quotes -> single quotes
* trailing commas

### CODE REVIEW

**Comment by Silverwolf90** [comment]
Provided the build passes and the regression tests pass without any changes, I think we can pretty confidently merge this set of automatic changes at once.

The basic summary of the transforms:

* var -> const/let
* anonymous functions -> arrow functions
* shorthand object properties
* minor spacing tweaks
* some indentation fixes

**Comment by 0xfe** [comment]
Thanks. All tests pass, and code looks way more consistent. Merging.

**Comment by SalahAdDin** [comment]
Which command and which package is?

**Comment by Silverwolf90** [comment]
Take a look at the first two steps here: https://github.com/0xfe/vexflow/wiki/Migrating-to-ESLint

**Comment by SalahAdDin** [comment]
Why don't use gulp?

**Comment by Silverwolf90** [comment]
How is gulp useful? Gulp is a build tool, not an AST transformer.

**Comment by SalahAdDin** [comment]
Gulp instead grunt.

**Pull request merged**
