### PR TITLE
Added two arabic accidentals: arabic-flat-half-flat and arabic-sharp-half-sharp 

### PR DESCRIPTION
**Pull request by MarianneAK**
Added the missing accidentals related to issue #710 to custom_glyphs:
arabic-sharp-half-sharp as "ashs" and arabic-flat-half-flat as "afhf"  shown below respectively:
Screenshot from 2019-10-20 18-55-51-1

These accidentals are frequently used in Modal Monodies, a type of music belonging to the Middle East and the Mediterranean cultures.
Feel free to review the code as I am not sure if anything else needs to be modified.

### CODE REVIEW

**Comment by 0xfe** [comment]
Thanks for the PR. Can you add these to the microtonals tests please?

**Comment by MarianneAK** [comment]
> 
> 
> Thanks for the PR. Can you add these to the microtonals tests please?

I added them to the "accidental_tests.js" and successfully ran the test with grunt. Do they need to be added anywhere else ?
Capture1

**Comment by 0xfe** [comment]
This is great, thanks! Merging.

**Comment by infojunkie** [comment]
Would be great if you could add these to the Wiki too at https://github.com/0xfe/vexflow/wiki/Microtonal-Support - thanks!

**Comment by sschmidTU** [comment]
I added them to the Wiki.
However, @infojunkie the images look a bit different from the rest because i generated them myself, how and with what specs did you generate these? Maybe you want to generate them like the ones from your repo?

Glyph | Mnemonic | Description | Notation System(s)
----- | -------- | ----------- | ------------------
image | ashs | Arabic-Sharp-Half-Sharp (1.25 tones sharp) | Arabic
image | afhf | Arabic-Flat-Half-Flat (1.25 tones flat) | Arabic

**Comment by infojunkie** [comment]
Looks like we both generated those images from `glyphs.html` and cutting the relevant area but our browsers may be rendering slightly differently... no big deal for me :joy:

**Comment by MarianneAK** [comment]
> I added them to the [Wiki page](https://github.com/0xfe/vexflow/wiki/Microtonal-Support).
> However, @infojunkie the images look a bit different from the rest because i generated them myself, how and with what specs did you generate these? Maybe you want to generate them like the ones from your repo?
> 
> Glyph	Mnemonic	Description	Notation System(s)
> image	ashs	Arabic-Sharp-Half-Sharp (1.25 tones sharp)	Arabic
> image	afhf	Arabic-Flat-Half-Flat (1.25 tones flat)	Arabic

Thank you!

**Pull request merged**
