### PR TITLE
API documentation: fix icons

### PR DESCRIPTION
**Pull request by rvilarl**
This PR includes:
- *.png are now treated as binary.
- `docco` npm package is no longer required.
- `typedoc` generates directly on `docs/api`, the copy step is no longer required.
- automatic updates of documentation for `Annotation` and `Factory`

### CODE REVIEW

**Comment by rvilarl** [comment]
Preview available in:

https://rvilarl.github.io/vexflow/api/

It is great how it works in a mobile now with the icons!

**Comment by rvilarl** [comment]
Ready to review and merge

**Comment by 0xfe** [comment]
Conflict from the merge I just did! :-)

**Comment by rvilarl** [comment]
The conflict are a little me complex, I will include the changes in #1239

**Pull request closed without merging**
